# Generated by Django 3.2.4 on 2021-06-14 06:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MtoJobCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(help_text='e.g Data entry', max_length=20, verbose_name='category')),
            ],
        ),
        migrations.CreateModel(
            name='Microtasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(help_text='e.g develop website', max_length=300)),
                ('target_date', models.DateTimeField(help_text='e.g 2021-10-25 14:30:59', null=True)),
                ('job_cost_AED', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('time_required', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('skills', models.CharField(help_text='e.g coding, data entry', max_length=500, verbose_name='skills')),
                ('number_of_people_required', models.PositiveIntegerField(help_text='e.g 2', validators=[django.core.validators.MinValueValidator(1)])),
                ('job_description', models.CharField(help_text='e.g car website', max_length=1000, verbose_name='job description')),
                ('upload_job_sample', models.FileField(upload_to='job_documents/job_samples/')),
                ('upload_job_instructions', models.FileField(upload_to='job_documents/job_instructions/')),
                ('type_of_TC', models.CharField(help_text='e.g Senior developer, tester & client', max_length=500, verbose_name='type of tc to be done')),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.mtojobcategories')),
            ],
        ),
    ]
