# Generated by Django 3.2.4 on 2021-06-14 08:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MAL_Requirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MAL_Job_Identification_Number', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
                ('Assembly_line_ID', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
                ('Name_of_the_Assembly_line', models.TextField()),
                ('Name_of_the_person_incharge_of_the_MAL', models.TextField()),
                ('Link_of_the_output_folder', models.FilePathField(path='job_documents/output')),
                ('microtask', models.CharField(max_length=100)),
                ('microtask_category', models.CharField(max_length=100)),
                ('Target_date', models.DateField()),
                ('Total_budget_allocated_for_the_job', models.IntegerField()),
                ('Job_description', models.TextField()),
                ('Uploadjob_sample', models.FileField(upload_to='jobsample')),
                ('UploadJob_instructions', models.FileField(upload_to='jobsinstruction')),
                ('Quantity_of_the_Job', models.IntegerField()),
                ('Link_of_the_Input_folder', models.FilePathField(path='job_documents/input')),
            ],
            options={
                'verbose_name': 'Mal Requiremet',
                'verbose_name_plural': 'Mal Requiremets',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
